activation: gelu
batch_size: 512
checkpoint_metric: acc/golden_acc
core_type: default
d_model: 512
decoder_type: default
dim_feedforward: 2048
dropout: 0.1
encoder_type: default
encoding_width: 8
final_layer_type: identity
mask_type: none
max_restart_lr: 0.00025
max_scratch_lr: 0.0005
max_sequence_length: 256
nhead: 8
num_layers: 8
score_rescale_mode: standardize
score_type: trans
