use_mockturtle: True
encoding_permutation_id: 0
bitwidth_input: 1
iterations: 1
chains: 2
chain_len: 2
chain_workers: 2
nb_runs: 1
res_folder: "res_00"
env_option: "auto"
experiment: "genial"
verbose: False
recipe_selection: "ALL"
save_option: "datarecord_compact"
strategy_name: "equal"
model_file: null
verilog_file: null
temperature: null
device_nb: null
selection_metric: "mockturtle_gates"
scripts_per_step: 1
compression_scripts_per_step: 3
skip_intermediate_metrics_extraction: True
measure_initial_timings_only: False
successive_compressions: 1
debug: False
command: null  # just for logging the command if run by command line
input_encoding: "twos_complement"
output_encoding: "twos_complement"
operation: "multiplication"
simulation_tb: False
simulation_tb_final: False
simulation_tb_save_all: False
tb_params_sim_mode: "normal_random"
tb_params_nb_iter: 10000
tb_params_std: 3.0
tb_params_mean: 0.0
tb_params_start_idx: 0
tb_params_end_idx: null
tb_params_seed: null
tb_params_sim_code: ""
design_run_id: null
n_states: null
encoding_dict_json_filepath: null
final_selection_metric: "mockturtle_gates"