activation: gelu
batch_size: 4096
checkpoint_metric: acc/golden_acc
core_type: default
criterion_type: huber_loss
d_model: 256
decoder_type: default
dim_feedforward: 512
dropout: 0.1
embedding_type: default
encoding_width: 4
final_layer_type: identity
lr_scheduler_type: warmup_constant_lindec_lr
mask_type: none
max_restart_lr: 0.00025
max_scratch_lr: 0.0004
max_sequence_length: 16
nhead: 8
num_layers: 5
optimizer_type: soap
score_rescale_mode: standardize
score_type: trans
n_cls_token: 1
