name: CI

on:
  push:
    branches: [ main, develop, dev/** ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  tests:
    name: Unit tests (Python 3.13)
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:27-dind
        env:
          DOCKER_TLS_CERTDIR: ""
        ports:
          - '2375:2375'
        options: >-
          --privileged
          --health-cmd "sh -c 'docker info >/dev/null 2>&1 || exit 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_TLS_VERIFY: "0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.SUBMODULES_TOKEN }}   # used for submodules too (HTTPS)

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Install project (editable) + test deps
        run: |
          # Create a local virtual environment managed by uv
          uv venv --python 3.13
          # Install the project and test dependencies into the venv
          uv pip install -e .
          uv pip install -r requirements_extra.txt || true

      - name: Run tests
        run: uv run pytest -q
