"experiment_name": "multiplier_4bi_8bo_permuti_allcells_notech"
"dir_name": "cmplx_test_run"
"ignore_user_prompts": True
"nb_workers": 60
"initial_dataset": null
"n_iter": 100
# ----- Training Parameters
"batch_size_trainer": 4000
"max_epochs_trainer": 300
"device": 0
"nb_init_designs": 4000
"score_type": "complexity"
"use_ssl_model": True
"trainer_version_number": 0  # Under which version number the training will be saved -- not used for loading
"ssl_model_checkpoint": "resources/pretrained_model/embedding/117_0.0102_000.ckpt"
"yml_config_path": "resources/pretrained_model/embedding/model_config-cmplx.yml"
# ----- Generation Parameters
"batch_size_proto": 4000
"max_epochs_proto": 500
"nb_gener_prototypes": 8000
# ----- Launch and analyze parameters
"synth_only": False
"cmplx_only": True
"skip_synth": True
"skip_swact": True
"skip_power": True
"skip_cmplx": False
"bulk_flow_dirname": null
"technology": null
