"experiment_name": "multiplier_4bi_8bo_permuti_allcells_notech_normal_only"
"dir_name": "exp_power_std3"
"ignore_user_prompts": True
"nb_workers": 120
"initial_dataset": null
"n_iter": 100
# ----- Training Parameters
"batch_size_trainer": 4500
"max_epochs_trainer": 300
"device": 1
"nb_init_designs": 20000
"score_type": "power"
"use_ssl_model": True
"trainer_version_number": 0  # Under which version number the training will be saved -- not used for loading
"ssl_model_checkpoint": "resources/pretrained_model/embedding/117_0.0102_000.ckpt"
"yml_config_path": "resources/pretrained_model/embedding/model_config.yml"
# ----- Generation Parameters
"batch_size_proto": 7000
"max_epochs_proto": 500
"nb_gener_prototypes": 14000
# ----- Launch and analyze parameters
"synth_only": False
"cmplx_only": False
"skip_synth": False
"skip_swact": True
"skip_power": False
"skip_cmplx": False
"bulk_flow_dirname": "power_out"
"technology": "asap7"
