/* Generated by Yosys 0.42 (git sha1 9b6afcf3f, g++ 13.2.0-23ubuntu4 -fPIC -Os) */

module mydesign_top(clk_ci, rst_ni, operand_a_i_0_, operand_a_i_1_, operand_a_i_2_, operand_b_i_0_, operand_b_i_1_, operand_b_i_2_, result_o_0_, result_o_1_, result_o_2_, result_o_3_, result_o_4_, result_o_5_);
wire _00_;
wire _01_;
wire _02_;
wire _03_;
wire _04_;
wire _05_;
wire _06_;
wire _07_;
wire _08_;
wire _09_;
wire _10_;
wire _11_;
wire _12_;
wire _13_;
wire _14_;
wire _15_;
wire _16_;
wire _17_;
wire _18_;
wire _19_;
wire _20_;
wire _21_;
wire _22_;
wire _23_;
wire _24_;
wire _25_;
wire _26_;
wire _27_;
wire _28_;
wire _29_;
wire _30_;
wire _31_;
wire _32_;
wire _33_;
wire _34_;
wire _35_;
wire _36_;
wire _37_;
wire _38_;
input clk_ci;
wire clk_ci;
wire \i_mydesign_comb.out_0_ ;
wire \i_mydesign_comb.out_1_ ;
wire \i_mydesign_comb.out_2_ ;
wire \i_mydesign_comb.out_3_ ;
wire \i_mydesign_comb.out_4_ ;
wire \i_mydesign_comb.out_5_ ;
input operand_a_i_0_;
wire operand_a_i_0_;
input operand_a_i_1_;
wire operand_a_i_1_;
input operand_a_i_2_;
wire operand_a_i_2_;
input operand_b_i_0_;
wire operand_b_i_0_;
input operand_b_i_1_;
wire operand_b_i_1_;
input operand_b_i_2_;
wire operand_b_i_2_;
output result_o_0_;
wire result_o_0_;
output result_o_1_;
wire result_o_1_;
output result_o_2_;
wire result_o_2_;
output result_o_3_;
wire result_o_3_;
output result_o_4_;
wire result_o_4_;
output result_o_5_;
wire result_o_5_;
input rst_ni;
wire rst_ni;
NOT  _39_ (
  .A(operand_a_i_0_),
  .Y(_00_)
);
NOT  _40_ (
  .A(operand_b_i_2_),
  .Y(_01_)
);
NAND  _41_ (
  .A(operand_b_i_0_),
  .B(operand_a_i_1_),
  .Y(_02_)
);
AND  _42_ (
  .A(operand_b_i_1_),
  .B(operand_a_i_0_),
  .Y(_03_)
);
XNOR  _43_ (
  .A(_02_),
  .B(_03_),
  .Y(\i_mydesign_comb.out_1_ )
);
NAND  _44_ (
  .A(operand_b_i_0_),
  .B(operand_a_i_2_),
  .Y(_04_)
);
AND  _45_ (
  .A(operand_b_i_1_),
  .B(operand_a_i_1_),
  .Y(_05_)
);
XNOR  _46_ (
  .A(_04_),
  .B(_05_),
  .Y(_06_)
);
NAND  _47_ (
  .A(_00_),
  .B(_06_),
  .Y(_07_)
);
ANDNOT  _48_ (
  .A(operand_b_i_1_),
  .B(operand_b_i_0_),
  .Y(_08_)
);
NAND  _49_ (
  .A(operand_a_i_1_),
  .B(_08_),
  .Y(_09_)
);
AND  _50_ (
  .A(operand_b_i_0_),
  .B(operand_a_i_0_),
  .Y(\i_mydesign_comb.out_0_ )
);
NAND  _51_ (
  .A(operand_a_i_2_),
  .B(\i_mydesign_comb.out_0_ ),
  .Y(_10_)
);
NAND  _52_ (
  .A(_09_),
  .B(_10_),
  .Y(_11_)
);
NAND  _53_ (
  .A(_01_),
  .B(_11_),
  .Y(_12_)
);
NAND  _54_ (
  .A(operand_a_i_0_),
  .B(operand_b_i_2_),
  .Y(_13_)
);
ANDNOT  _55_ (
  .A(_09_),
  .B(_13_),
  .Y(_14_)
);
NAND  _56_ (
  .A(_04_),
  .B(_14_),
  .Y(_15_)
);
AND  _57_ (
  .A(_12_),
  .B(_15_),
  .Y(_16_)
);
NAND  _58_ (
  .A(_07_),
  .B(_16_),
  .Y(\i_mydesign_comb.out_2_ )
);
OR  _59_ (
  .A(operand_b_i_0_),
  .B(operand_b_i_1_),
  .Y(_17_)
);
NAND  _60_ (
  .A(operand_a_i_2_),
  .B(_17_),
  .Y(_18_)
);
NAND  _61_ (
  .A(operand_b_i_2_),
  .B(operand_a_i_1_),
  .Y(_19_)
);
ANDNOT  _62_ (
  .A(_00_),
  .B(_19_),
  .Y(_20_)
);
NAND  _63_ (
  .A(_18_),
  .B(_20_),
  .Y(_21_)
);
MUX  _64_ (
  .A(operand_b_i_1_),
  .B(operand_a_i_1_),
  .S(operand_b_i_0_),
  .Y(_22_)
);
NAND  _65_ (
  .A(_01_),
  .B(_22_),
  .Y(_23_)
);
XNOR  _66_ (
  .A(operand_b_i_0_),
  .B(operand_b_i_1_),
  .Y(_24_)
);
OR  _67_ (
  .A(_03_),
  .B(_24_),
  .Y(_25_)
);
OR  _68_ (
  .A(operand_a_i_1_),
  .B(_25_),
  .Y(_26_)
);
NAND  _69_ (
  .A(_23_),
  .B(_26_),
  .Y(_27_)
);
NAND  _70_ (
  .A(operand_a_i_2_),
  .B(_27_),
  .Y(_28_)
);
OR  _71_ (
  .A(operand_a_i_1_),
  .B(_13_),
  .Y(_29_)
);
OR  _72_ (
  .A(operand_b_i_1_),
  .B(_29_),
  .Y(_30_)
);
NAND  _73_ (
  .A(_01_),
  .B(_02_),
  .Y(_31_)
);
ANDNOT  _74_ (
  .A(_03_),
  .B(operand_a_i_2_),
  .Y(_32_)
);
NAND  _75_ (
  .A(_31_),
  .B(_32_),
  .Y(_33_)
);
AND  _76_ (
  .A(_30_),
  .B(_33_),
  .Y(_34_)
);
AND  _77_ (
  .A(_28_),
  .B(_34_),
  .Y(_35_)
);
NAND  _78_ (
  .A(_21_),
  .B(_35_),
  .Y(\i_mydesign_comb.out_3_ )
);
NAND  _79_ (
  .A(operand_b_i_2_),
  .B(operand_a_i_2_),
  .Y(_36_)
);
AND  _80_ (
  .A(_13_),
  .B(_18_),
  .Y(_37_)
);
NAND  _81_ (
  .A(_19_),
  .B(_37_),
  .Y(_38_)
);
AND  _82_ (
  .A(_36_),
  .B(_38_),
  .Y(\i_mydesign_comb.out_5_ )
);
XNOR  _83_ (
  .A(_36_),
  .B(_38_),
  .Y(\i_mydesign_comb.out_4_ )
);
DFF_PN0  result_o_0__reg (
  .C(clk_ci),
  .D(\i_mydesign_comb.out_0_ ),
  .Q(result_o_0_),
  .R(rst_ni)
);
DFF_PN0  result_o_1__reg (
  .C(clk_ci),
  .D(\i_mydesign_comb.out_1_ ),
  .Q(result_o_1_),
  .R(rst_ni)
);
DFF_PN0  result_o_2__reg (
  .C(clk_ci),
  .D(\i_mydesign_comb.out_2_ ),
  .Q(result_o_2_),
  .R(rst_ni)
);
DFF_PN0  result_o_3__reg (
  .C(clk_ci),
  .D(\i_mydesign_comb.out_3_ ),
  .Q(result_o_3_),
  .R(rst_ni)
);
DFF_PN0  result_o_4__reg (
  .C(clk_ci),
  .D(\i_mydesign_comb.out_4_ ),
  .Q(result_o_4_),
  .R(rst_ni)
);
DFF_PN0  result_o_5__reg (
  .C(clk_ci),
  .D(\i_mydesign_comb.out_5_ ),
  .Q(result_o_5_),
  .R(rst_ni)
);
endmodule
